[project]
name = "threat-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fasttext>=0.9.3",
    "libsql>=0.1.11",
    "numpy==1.26.4",
    "pandas==2.2.2",
    "pyarrow>=23.0.1",
    "requests>=2.33.0",
]
