name: Process New Repos

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    env:
      CB_API_KEY: ${{ secrets.CODEBERG_TOKEN }}
      GH_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh

      - name: Set up Python
        run: uv python install 3.10

      - name: sync deps.
        run: uv sync

      - name: install hf
        run: curl -LsSf https://hf.co/cli/install.sh | bash

      - name: download model
        run: curl -L -o model.bin https://github.com/Zigistry/threat-detection/releases/download/threat-detection-model/model.bin

      - name: Download the database
        run: wget -O ./zigistry.db https://huggingface.co/buckets/Zigistry/Zigistry/resolve/zigistry.db?download=true

      - name: Run process script
        run: uv run python src/process_and_add_new_repos.py

      - name: push updated database
        run: hf cp ./zigistry.db hf://buckets/Zigistry/Zigistry/zigistry.db
